name: build-package
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Target package'
        type: string
        default: 'rclcpp'
        required: true
run-name: Build up to package ${{ inputs.package }}


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p ros_workspace/src
    - uses: actions/checkout@v3
      with:
        path: ros_workspace/src/myrepo
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: |
        echo ${{ inputs.package }}
        ls ${{ github.workspace }}
        echo 'HOME'
        ls ros_workspace/src
        echo 'DONE'
