name: learn-github-actions
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Target package'
        type: string
        default: 'rclcpp'
        required: true
run-name: Build up to package ${{ inputs.package }}
branding:
  icon: 'award'
  color: 'green'


jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install -g bats
    - run: bats -v
    - run: echo ${{ inputs.package }}