name: build-package
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Target package'
        type: string
        default: 'rclcpp'
        required: true
run-name: Build up to package ${{ inputs.package }}


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p ${{ github.workspace }}/src
    - uses: actions/checkout@v3
      with:
        path: ${{ github.workspace }}/src/
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: |
        echo ${{ inputs.package }}
        echo ${{ github.workspace }}
        cat ${{ github.workspace }}/src/hello.py
        echo 'DONE'
