name: build-package
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Target package'
        type: string
        default: 'rclcpp'
        required: true
run-name: Build up to package ${{ inputs.package }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: ./src/
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install -g bats
    - run: bats -v
    - run: |
        echo ${{ inputs.package }}
        echo ${{ github.workspace }}
        cat ./src/workflows/src/hello.py
        echo 'DONE'
