name: build-package
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Target package'
        type: string
        default: 'rclcpp'
        required: true
run-name: Build up to package ${{ inputs.package }}


jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      TARGET_PLATFORM: emscripten-32
      RMW_IMPLEMENTATION: rmw_wasm
      ROS_VERSION: 2
      ROS_DISTRO: humble

    steps:

    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 1.38.40
      
    - name: Verify emsdk
      run: emcc -v      

    - name: Create ROS workspace
      run: mkdir -p ros_workspace/src

    - name: Install rmw_wasm
      uses: actions/checkout@v3
      with:
        path: ros_workspace/src/myrepo

    - name: Create environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: ros_workspace/src/myrepo/src/env.yaml
        environment-name: ros-env
        micromamba-version: '1.4.1'
    
    - name: Activate environment
      run: |
        eval "$(micromamba shell hook --shell=bash)"
        micromamba activate ros-env

    - name: Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: |
        echo ${{ inputs.package }}
        ls ${{ github.workspace }}
        echo 'HOME'
        cat ros_workspace/src/myrepo/src/hello.py
        cd ros_workspace
        touch tst.txt
        echo 'NEW FILE'
        ls .
        echo 'MAMAB'
        which micromamba
        echo 'DONE'
